// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mneuymiezgkxcmpwawrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uZXV5bWllemdreGNtcHdhd3JkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNzgxODAsImV4cCI6MjA3NDY1NDE4MH0.6s5Ho4-106ec2FRs29Af11_xQSsC6QLRn5GFCoXqv78";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});